version: "3.9"
services:
  db: 
    build: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "80:3000" ## Customize local port
    depends_on:
      - db
